apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ingess.class: nginx
spec:
  rules:
  - http:
      paths:      
        - path: "/"
          backend:
            serviceName: client-cluster-ip-service
            servicePort: 3000
        - path: "/api/"
          backend:
            serviceName: server-cluster-ip-service
            servicePort: 5000
